### PR TITLE
[fix-debounce]: should not send values repeatedly

### LINKED ISSUE #46: Debounce keeps emitting values even though debounced publisher is not publishing
Debounce seems to get into an endless loop emitting last received value.
This code:

```Swift
 let pub = PassthroughSubject<Int, Never>()
        
        pub
            .debounce(for: 1.0, scheduler: DispatchQueue.main.cx)
            .sink(receiveValue: {
                print("received: \($0) at: \(Date())")
            })
            .store(in: &subscribers)
        
        (0...10).forEach(pub.send)
```

Gives this result:

```
received: 10 at: 2019-11-07 10:16:58 +0000
received: 10 at: 2019-11-07 10:16:59 +0000
received: 10 at: 2019-11-07 10:17:00 +0000
received: 10 at: 2019-11-07 10:17:01 +0000
received: 10 at: 2019-11-07 10:17:02 +0000
received: 10 at: 2019-11-07 10:17:03 +0000
received: 10 at: 2019-11-07 10:17:04 +0000
received: 10 at: 2019-11-07 10:17:05 +0000
received: 10 at: 2019-11-07 10:17:06 +0000
received: 10 at: 2019-11-07 10:17:07 +0000
received: 10 at: 2019-11-07 10:17:08 +0000
received: 10 at: 2019-11-07 10:17:09 +0000
received: 10 at: 2019-11-07 10:17:10 +0000
received: 10 at: 2019-11-07 10:17:11 +0000
received: 10 at: 2019-11-07 10:17:12 +0000
received: 10 at: 2019-11-07 10:17:13 +0000
received: 10 at: 2019-11-07 10:17:14 +0000
```

### PR DESCRIPTION
**Pull request by luoxiu**
fix #46 

Sorry for my carelessness. 🤦‍♂️

### CODE REVIEW

**Comment by luoxiu** [comment]
`debounce` and `throttle` still have a lot of edging cases that need to be verified, I will focus on them this weekend after I have solved #37  .

File: Package.swift [hunk 1]
```diff
@@ -120,7 +123,7 @@ for target in package.targets where target.isTest || target.name == "CXTestUtili
     target.swiftSettings.append(contentsOf: combineImp.swiftSettings)
 }
 
-if combineImp == .combine && env["CX_CONTINUOUS_INTEGRATION"] != nil {
+if combineImp == .combine {
```
Comment (ddddxxx) [inline Package.swift]: So client can't use CXShim on lower version OS 🤔?

Comment (luoxiu) [reply Package.swift]: If he is using `combine`...

Comment (luoxiu) [reply Package.swift]: `canImport(combine)` doesn't mean you can use combine, you still need to update the deployment target to macos10.15+/ios13+

Comment (luoxiu) [reply Package.swift]: We do need "CX_CONTINUOUS_INTEGRATION"!

**Review by ddddxxx — APPROVED** [review]
